<a href="https://colab.research.google.com/github/taraumutoni/Machine_Learning_course_UGent_D012554_kaggle/blob/master/XGBoost.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%matplotlib inline
import pandas as pd

In [0]:
trainset = pd.read_csv("https://raw.githubusercontent.com/sdgroeve/Machine_Learning_course_UGent_D012554_kaggle/master/eeg_train.csv")

testset = pd.read_csv("https://raw.githubusercontent.com/sdgroeve/Machine_Learning_course_UGent_D012554_kaggle/master/eeg_test.csv")

In [0]:
trainset_copy = trainset.copy()
testset_copy = testset.copy()
label_column = trainset.pop('label')
index_column = testset.pop('index')

In [0]:
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import numpy as np


scaler = StandardScaler()
scaler.fit(trainset)
trainset_scaled = scaler.transform(trainset)
testset_scaled = scaler.transform(testset)

In [0]:
trainset_scaled= pd.DataFrame(data=trainset_scaled)
testset_scaled = pd.DataFrame(data=testset_scaled)

In [18]:
!pip install xgboost

In [19]:
!pip install --upgrade xgboost

Requirement already up-to-date: xgboost in /usr/local/lib/python3.6/dist-packages (1.0.2)


In [20]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

model = XGBClassifier()
model.fit(trainset_scaled, label_column)

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints=None,
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='binary:logistic', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method=None,
              validate_parameters=False, verbosity=None)

In [21]:
from sklearn.model_selection import GridSearchCV # tried the gridsearch for C and gamma value

base_score = [0.001,0.01,0.1,1,10,100]
gamma_value = [0.001,0.01,0.1,1,10,100]
max_depth = [1,10,20]
min_child_weight = [1,10]
model = XGBClassifier()
params = dict(base_score=base_score, gamma=gamma_value, max_depth=max_depth, min_child_weight=min_child_weight)# grid of parameters you want to search the optimal value
grid_search = GridSearchCV(model, param_grid=params, cv=10)
grid_search.fit(trainset_scaled, label_column)

print(grid_search.best_params_)

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
xgboost.core.XGBoostError: [20:05:23] /workspace/src/objective/./regression_loss.h:89: Check failed: base_score > 0.0f && base_score < 1.0f: base_score must be in (0,1) for logistic loss, got: 1
Stack trace:
  [bt] (0) /usr/local/lib/python3.6/dist-packages/xgboost/./lib/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x54) [0x7f5918c8f614]
  [bt] (1) /usr/local/lib/python3.6/dist-packages/xgboost/./lib/libxgboost.so(xgboost::obj::LogisticRegression::ProbToMargin(float)+0xbf) [0x7f5918f3523f]
  [bt] (2) /usr/local/lib/python3.6/dist-packages/xgboost/./lib/libxgboost.so(xgboost::LearnerImpl::Configure()+0xcd9) [0x7f5918d814c9]
  [bt] (3) /usr/local/lib/python3.6/dist-packages/xgboost/./lib/libxgboost.so(xgboost::LearnerImpl::UpdateOneIter(int, xgboost::DMatrix*)+0x6d) [

{'base_score': 0.1, 'gamma': 0.01, 'max_depth': 20, 'min_child_weight': 1}


KeyboardInterrupt: ignored

In [28]:
model = XGBClassifier()
model.fit(trainset_scaled, label_column)


XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints=None,
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='binary:logistic', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method=None,
              validate_parameters=False, verbosity=None)

In [29]:
model.predict_proba(testset_scaled)# XGBoost predicts probabilities


array([[0.99767953, 0.00232046],
       [0.9181285 , 0.08187151],
       [0.9967346 , 0.00326536],
       ...,
       [0.00803334, 0.99196666],
       [0.05941659, 0.9405834 ],
       [0.99131674, 0.00868324]], dtype=float32)

In [34]:
pred_boost = model.predict(testset_scaled)
print(pred_boost)

[0 0 0 ... 1 1 0]


In [70]:
mod = XGBClassifier(base_score=0.8, max_depth=8, min_child_weight=1,gamma=0)
mod.fit(trainset_scaled, label_column)
#base_score=0.6, max_depth=8, min_child_weight=1,gamma=0#88.40%
#base_score=0.8, max_depth=8, min_child_weight=1,gamma=0 # 88.44%

XGBClassifier(base_score=0.8, booster=None, colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints=None,
              learning_rate=0.300000012, max_delta_step=0, max_depth=8,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='binary:logistic', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method=None,
              validate_parameters=False, verbosity=None)

In [71]:
mod_predict = mod.predict(testset_scaled)
print(mod_predict)

[0 0 0 ... 1 1 0]


In [35]:
from sklearn import svm
from sklearn.svm import SVC

clf = svm.SVC(C= 10, kernel='rbf',gamma=1, probability=True) 
 #gamma scales the influence two observations have on each other depending on the distance
clf.fit(trainset_scaled, label_column)

SVC(C=10, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=1, kernel='rbf', max_iter=-1,
    probability=True, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

In [37]:
pred_SVM = clf.predict(testset_scaled)
print(pred_SVM)

[0 0 0 ... 1 1 0]


In [39]:
from sklearn.metrics import accuracy_score
#evaluate 2 model predictions
accuracy = accuracy_score( pred_SVM, pred_boost)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 87.88%


In [69]:
accuracy = accuracy_score( pred_SVM, mod_predict)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 88.44%


In [0]:
prediction_test = pd.DataFrame(columns=['index','label'])
prediction_test['index'] = index_column
prediction_test['label'] = mod_predict 

 

filename = "XGBoost1.csv"
prediction_test.to_csv(filename, index=False)